repository:
  # Nazwa repozytorium
  name: CardActions.Api

  # Opis projektu
  description: Card Actions API

  # Strona projektu
  homepage: https://github.com/${{ github.repository_owner }}/CardActions.Api

  # Widoczność repozytorium (public, private)
  private: false

  # Czy repozytorium jest archiwizowane
  archived: false

  # Gałąź domyślna
  default_branch: main

  # Zabezpieczenia - wymagana recenzja kodu
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

# Reguły zabezpieczeń gałęzi
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["build"]
      enforce_admins: false
      restrictions:
        users: []
        teams: []
        apps: []

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["build"]
      enforce_admins: false
      restrictions:
        users: []
        teams: []
        apps: [] 