name: Repository Protection Rules

on:
  push:
    branches:
      - main
    paths:
      - '.github/CODEOWNERS'
      - '.github/workflows/repo-settings.yml'

jobs:
  protection:
    name: Enforce Branch Protection
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate CODEOWNERS
        run: |
          if [ -f .github/CODEOWNERS ]; then
            echo "CODEOWNERS file exists, validating..."
            grep -q "@leszekszpunar" .github/CODEOWNERS || 
              (echo "CODEOWNERS file must include @leszekszpunar as an owner" && exit 1)
            echo "CODEOWNERS validation passed"
            
            # Wyświetl instrukcje dotyczące branch protection
            echo "===== WAŻNE PRZYPOMNIENIE ====="
            echo "Zalecane ustawienia zabezpieczeń dla gałęzi głównych (main, develop):"
            echo "1. Require pull request reviews before merging"
            echo "   - At least 1 approval required"
            echo "   - Dismiss stale pull request approvals when new commits are pushed"
            echo "   - NIE WŁĄCZAJ 'Require review from Code Owners', bo zablokujesz sam siebie!"
            echo "2. Require status checks to pass before merging"
            echo "   - Require branches to be up to date before merging"
            echo "   - Required status check: build"
            echo "Te ustawienia są dostępne w: Settings > Branches > Branch protection rules"
            echo "==============================="
          else
            echo "CODEOWNERS file does not exist, creating..."
            mkdir -p .github
            echo "# All repository owners must approve changes" > .github/CODEOWNERS
            echo "* @leszekszpunar" >> .github/CODEOWNERS
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .github/CODEOWNERS
            git commit -m "Add CODEOWNERS file"
            git push
          fi 