name: Repository Protection Rules

on:
  push:
    branches:
      - main
    paths:
      - '.github/CODEOWNERS'
      - '.github/workflows/repo-settings.yml'

jobs:
  protection:
    name: Enforce Branch Protection
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install needed packages
        run: sudo apt-get install -y jq curl

      - name: Validate CODEOWNERS
        run: |
          if [ -f .github/CODEOWNERS ]; then
            echo "CODEOWNERS file exists, validating..."
            grep -q "@${{ github.repository_owner }}" .github/CODEOWNERS || 
              (echo "CODEOWNERS file must include @${{ github.repository_owner }} as an owner" && exit 1)
            echo "CODEOWNERS validation passed"
          else
            echo "CODEOWNERS file does not exist, creating..."
            mkdir -p .github
            echo "# All repository owners must approve changes" > .github/CODEOWNERS
            echo "* @${{ github.repository_owner }}" >> .github/CODEOWNERS
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .github/CODEOWNERS
            git commit -m "Add CODEOWNERS file"
            git push
          fi
          
      - name: Create PR Protection Issue
        if: ${{ always() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const issueTitle = 'Branch Protection Reminder';
            const issueBody = `
            ## Branch Protection Settings Reminder
            
            Zalecane ustawienia zabezpieczeń dla gałęzi głównych (main, develop):

            ### Zalecane ustawienia dla indywidualnego dewelopera:
            - ✅ Require pull request reviews before merging
              - At least 1 approval required 
              - Dismiss stale pull request approvals when new commits are pushed
              - ⚠️ **NIE WŁĄCZAJ** "Require review from Code Owners", ponieważ bez innych współpracowników zablokujesz sam siebie!
            - ✅ Require status checks to pass before merging
              - Require branches to be up to date before merging
              - Required status check: build
            
            Te ustawienia są dostępne w:
            **Settings > Branches > Branch protection rules**
            
            To przypomnienie utworzono: ${new Date().toISOString()}.
            `;
            
            // Check for existing issue
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'open',
              creator: 'github-actions[bot]',
            });
            
            const existingIssue = issues.data.find(issue => issue.title === issueTitle);
            
            if (!existingIssue) {
              // Create a new issue
              await github.rest.issues.create({
                owner,
                repo,
                title: issueTitle,
                body: issueBody,
                labels: ['documentation']
              });
              console.log('Created a new branch protection reminder issue');
            } else {
              console.log('Branch protection reminder issue already exists:', existingIssue.html_url);
            } 